# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
import numpy as np

a=np.arange(6)

print(a.sum())
print(np.sum(a))
print(sum(a))

15
15
15


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [23]:
# 記得先 Import 正確的套件
import numpy as np

a = np.random.random((5,5))
#公式：x-mean()/std()
b = a.mean()
c= a.std()
print((a-b)/c)

[[-0.06930097  0.93700686  1.64441265 -1.38956004 -1.53021512]
 [-0.42982096  0.29988004 -1.32855056  0.08946585 -0.67392588]
 [ 1.70466621  0.3459363  -0.0824708  -0.34300224  1.35078352]
 [-1.66979975 -1.1537898   1.16151795 -0.0814684   1.02673301]
 [-0.61912727 -0.20116569  1.23261929  0.65353725 -0.87436145]]


array([[0.13197583, 0.1034873 , 0.        , 0.31390653, 0.35846645],
       [0.14777047, 0.28417508, 0.75999011, 0.29030305, 0.72055306],
       [0.98492508, 0.41249799, 1.        , 0.39756699, 0.39109584],
       [0.85537752, 0.84696945, 0.69635415, 0.86720675, 0.61212718],
       [0.24295928, 0.99120832, 0.09074347, 0.78251208, 0.57787873]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [31]:
a = np.random.randint(100,size=10)
print(a)
b = a.max()
print(b)
a[a==b]=-1
print(a)

[81 42 70 56 45 49 20 86 89 96]
96
[81 42 70 56 45 49 20 86 89 -1]
